#!/bin/bash

set -e

cd "$(dirname "$0")/.."

poetry run ruff format --check graphs2go tests
poetry run ruff check graphs2go tests
poetry run mypy graphs2go tests
export PYTHONPATH=$PWD
poetry run pytest tests
